config/routes.rb
Picv::Application.routes.draw do
  

  resources :notas

  resources :denuncias

  resources :expedientes

  resources :sucursales

  resources :municipios

  resources :departamentos

  resources :instituciones

    

  match 'sms/index' => 'sms#index'
  
  resources :archivos

  match 'denuncias/expediente/:id' => 'denuncias#new_con_expediente', :as => :expediente_denuncia

  resources :usuarios
  resources :sesiones
  root :to => "expedientes#index"
  get "logout" => "sesiones#destroy", :as => "logout"
  get "login" => "sesiones#new", :as => "login"
  get "signup" => "usuarios#new", :as => "signup"
end

app/models/expediente.rb
class Expediente < ActiveRecord::Base
  belongs_to :municipio
  has_many :denuncias
  attr_accessible :apellido1, :apellido2, :documento_identidad, :edad, :email, :nombre, 
  				  :sexo, :telefono, :zona, :ocupacion, :lugar_trabajo, :telefono_trabajo,
  				  :municipio_trabajo_id, :nivel_educativo, :estado_familiar, :sostenimiento_familiar,
  				  :discapacidad_fisica, :discapacidad_mental, :municipio_id, :direccion_trabajo
end

app/controllers/expedientes_controller.rb
class ExpedientesController < ApplicationController
  
  load_and_authorize_resource
  
  # GET /expedientes
  # GET /expedientes.json
  def index
    @expedientes = Expediente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @expedientes }
    end
  end

  # GET /expedientes/1
  # GET /expedientes/1.json
  def show
    @expediente = Expediente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @expediente }
    end
  end

  # GET /expedientes/new
  # GET /expedientes/new.json
  def new
    @expediente = Expediente.new
    @municipios = Municipio.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @expediente }
    end
  end

  # GET /expedientes/1/edit
  def edit
    @expediente = Expediente.find(params[:id])
    @municipios = Municipio.all
  end

  # POST /expedientes
  # POST /expedientes.json
  def create
    @expediente = Expediente.new(params[:expediente])
    
    respond_to do |format|
      if @expediente.save
        format.html { redirect_to @expediente, notice: 'Expediente was successfully created.' }
        format.json { render json: @expediente, status: :created, location: @expediente }
      else
        format.html { render action: "new" }
        format.json { render json: @expediente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /expedientes/1
  # PUT /expedientes/1.json
  def update
    @expediente = Expediente.find(params[:id])

    respond_to do |format|
      if @expediente.update_attributes(params[:expediente])
        format.html { redirect_to @expediente, notice: 'Expediente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @expediente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expedientes/1
  # DELETE /expedientes/1.json
  def destroy
    @expediente = Expediente.find(params[:id])
    @expediente.destroy

    respond_to do |format|
      format.html { redirect_to expedientes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/expedientes_helper.rb
module ExpedientesHelper
end

app/views/expedientes/_form.html.erb
<%= form_for(@expediente) do |f| %>
  <% if @expediente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expediente.errors.count, "error") %> prohibited this expediente from being saved:</h2>

      <ul>
      <% @expediente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido1 %><br />
    <%= f.text_field :apellido1 %>
  </div>
  <div class="field">
    <%= f.label :apellido2 %><br />
    <%= f.text_field :apellido2 %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br />
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :documento_identidad %><br />
    <%= f.text_field :documento_identidad %>
  </div>
  <div class="field">
    <%= f.label :edad %><br />
    <%= f.number_field :edad %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br />
    <%= f.text_field :sexo %>
  </div>
  <div class="field">
    <%= f.label :municipio %><br />
    <%= collection_select(:expediente, :municipio_id, @municipios, :id, :nombre_completo, {:prompt => false })  %>

  </div>
  <div class="field">
    <%= f.label :zona %><br />
    <%= select_tag(:zona, options_for_select([['Rural', 'Rural'], ['Urbana', 'Urbana'], ['Marginal', 'Marginal']])) %>
  </div>
  <div class="field">
    <%= f.label :ocupacion %><br />
    <%= f.text_field :ocupacion %>
  </div>
  <div class="field">
    <%= f.label :lugar_trabajo %><br />
    <%= f.text_field :lugar_trabajo %>
  </div>
  <div class="field">
    <%= f.label :telefono_trabajo %><br />
    <%= f.text_field :telefono_trabajo %>
  </div>
  <div class="field">
    <%= f.label :direccion_trabajo %><br />
    <%= f.text_field :direccion_trabajo %>
  </div>
  <div class="field">
    <%= f.label :nivel_educativo %><br />
    <%= f.text_field :nivel_educativo %>
  </div>
  <div class="field">
    <label>Zona Trabajo</label><br />
    <%= select_tag(:zona, options_for_select([['Rural', 'Rural'], ['Urbana', 'Urbana'], ['Marginal', 'Marginal']])) %>
  </div>
  <div class="field">
    <%= f.label :estado_familiar %><br />
    <%= f.text_field :estado_familiar %>
  </div>
  <div class="field">
    <%= f.label :sostenimiento_familiar %><br />
    <%= f.text_field :sostenimiento_familiar %>
  </div>
  <div class="field">
    <%= f.label :discapacidad_fisica %><br />
    <%= f.text_field :discapacidad_fisica %>
  </div>
  <div class="field">
    <%= f.label :discapacidad_mental %><br />
    <%= f.text_field :discapacidad_mental %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expedientes/edit.html.erb
<% content_for :content do %>

<ul class="breadcrumb">
                  <li>Estás en:</li>
                  <li>
                    <%= link_to expedientes_path do %>
                        Expedientes
                    <% end %>                  
                    <span class="divider">
                      <span class="icon16 icomoon-icon-arrow-right">/</span>
                    </span>
                  </li>
                  <li>
                    <%= link_to expediente_path(@expediente) do %>
                        Expediente No. <%= @expediente.id %>
                    <% end %>                  
                    <span class="divider">
                      <span class="icon16 icomoon-icon-arrow-right">/</span>
                    </span>
                  </li>
                  <li class="active">Editando Expediente</li>
</ul>

<h1>Editing expediente</h1>

<%= render 'form' %>

<%= link_to 'Show', @expediente %> |
<%= link_to 'Back', expedientes_path %>
<% end %>

<%= render :template => 'layouts/dashboard' %>

app/views/expedientes/index.html.erb
<% content_for :content do %>

<ul class="breadcrumb">
    <li>Estás en:</li>
    <li class="active">Expedientes</li>
</ul>


<h1>Expedientes</h1>

<table class="table table-bordered">
  <tr>
    <th width="90%" >Expediente</th>
    <th width="10%">Acciones</th>
  </tr>

<% @expedientes.each do |expediente| %>
  <tr>
    <td><b>Nombre:</b> <i><%= expediente.nombre %>
        <%= expediente.apellido1 %>
        <%= expediente.apellido2 %></i><br>
        <b>Documento de Identidad:</b> <%= expediente.documento_identidad %><br>
        <b>Edad:</b> <%= expediente.edad %><br>
        <b>Sexo:</b> <%= expediente.sexo %> </td>
        
        <td>
            <%= link_to 'Ver', expediente %>
        </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Agregar Expediente', new_expediente_path %>
<% end %>

<%= render :template => 'layouts/dashboard' %>

app/views/expedientes/new.html.erb
<% content_for :content do %>
<h1>New expediente</h1>

<%= render 'form' %>

<%= link_to 'Back', expedientes_path %>
<% end %>

<%= render :template => 'layouts/dashboard' %>

app/views/expedientes/show.html.erb
<% content_for :content do %>

<ul class="breadcrumb">
                  <li>Estás en:</li>
                  <li>
                    <%= link_to expedientes_path do %>
                        Expedientes
                    <% end %>                  
                    <span class="divider">
                      <span class="icon16 icomoon-icon-arrow-right">/</span>
                    </span>
                  </li>
                  <li class="active">Expediente No. <%= @expediente.id %></li>
</ul>


<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @expediente.nombre %>
</p>

<p>
  <b>Apellido1:</b>
  <%= @expediente.apellido1 %>
</p>

<p>
  <b>Apellido2:</b>
  <%= @expediente.apellido2 %>
</p>

<p>
  <b>Telefono:</b>
  <%= @expediente.telefono %>
</p>

<p>
  <b>Email:</b>
  <%= @expediente.email %>
</p>

<p>
  <b>Dui:</b>
  <%= @expediente.documento_identidad %>
</p>

<p>
  <b>Edad:</b>
  <%= @expediente.edad %>
</p>

<p>
  <b>Sexo:</b>
  <%= @expediente.sexo %>
</p>

<p>
  <b>Municipio:</b>
  <%= @expediente.municipio.nombre_completo if @expediente.municipio %>
</p>


<h3>Denuncias</h3>

<table class="table table-bordered">
  <tr>
    <th width="90%" >Denuncia</th>
    <th width="10%">Acciones</th>
  </tr>

<% @expediente.denuncias.each do |denuncia| %>
  <tr>
    <td>
      <b>Fecha:</b> <i><%= denuncia.created_at %></i><br>
      <b>Tipo:</b> <i><%= denuncia.tipo %></i><br>
      <b>Direccion:</b> <i><%= denuncia.municipio_hechos %></i><br>
      <b>Descripcion:</b> <i><%= denuncia.descripcion %></i><br>
    </td>
        
    <td>
            <%= link_to 'Ver', denuncia %>
        </td>
  </tr>
<% end %>
</table>


<%= link_to 'Editar', edit_expediente_path(@expediente) %> | <%= link_to 'Agregar Denuncia', expediente_denuncia_path(@expediente.id) %>

<% end %>

<%= render :template => 'layouts/dashboard' %>