config/routes.rb
Picv::Application.routes.draw do
  

  resources :notas

  resources :denuncias

  resources :expedientes

  resources :sucursales

  resources :municipios

  resources :departamentos

  resources :instituciones

    

  match 'sms/index' => 'sms#index'
  
  resources :archivos

  match 'denuncias/expediente/:id' => 'denuncias#new_con_expediente', :as => :expediente_denuncia

  resources :usuarios
  resources :sesiones
  root :to => "expedientes#index"
  get "logout" => "sesiones#destroy", :as => "logout"
  get "login" => "sesiones#new", :as => "login"
  get "signup" => "usuarios#new", :as => "signup"
end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
  attr_accessible :nombre
  has_many:municipios
  validates :nombre, :presence => true
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  
  load_and_authorize_resource
  
  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departamentos }
    end
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
    @departamento = Departamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @departamento }
    end
  end

  # GET /departamentos/new
  # GET /departamentos/new.json
  def new
    @departamento = Departamento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @departamento }
    end
  end

  # GET /departamentos/1/edit
  def edit
    @departamento = Departamento.find(params[:id])
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(params[:departamento])

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: 'Departamento was successfully created.' }
        format.json { render json: @departamento, status: :created, location: @departamento }
      else
        format.html { render action: "new" }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departamentos/1
  # PUT /departamentos/1.json
  def update
    @departamento = Departamento.find(params[:id])

    respond_to do |format|
      if @departamento.update_attributes(params[:departamento])
        format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento = Departamento.find(params[:id])
    @departamento.destroy

    respond_to do |format|
      format.html { redirect_to departamentos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/departamentos/_form.html.erb
<%= form_for(@departamento) do |f| %>
  <% if @departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% @departamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<% content_for :content do %>
<h1>Editing departamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>
<% end %>

<%= render :template => 'layouts/dashboard' %>

app/views/departamentos/index.html.erb
<% content_for :content do %>
<h1>Listing departamentos</h1>

<table class="table table-bordered">
  <tr>
    <th>Nombre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @departamentos.each do |departamento| %>
  <tr>
    <td><%= departamento.nombre %></td>
    <td><%= link_to 'Show', departamento %></td>
    <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
    <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Departamento', new_departamento_path %>
<% end %>

<%= render :template => 'layouts/dashboard' %>

app/views/departamentos/new.html.erb
<% content_for :content do %>
<h1>New departamento</h1>

<%= render 'form' %>

<%= link_to 'Back', departamentos_path %>
<% end %>

<%= render :template => 'layouts/dashboard' %>

app/views/departamentos/show.html.erb
<% content_for :content do %>
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @departamento.nombre %>
</p>


<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>
<% end %>

<%= render :template => 'layouts/dashboard' %>