config/routes.rb
Picv::Application.routes.draw do
  

  resources :notas

  resources :denuncias

  resources :expedientes

  resources :sucursales

  resources :municipios

  resources :departamentos

  resources :instituciones

    

  match 'sms/index' => 'sms#index'
  
  resources :archivos

  match 'denuncias/expediente/:id' => 'denuncias#new_con_expediente', :as => :expediente_denuncia

  resources :usuarios
  resources :sesiones
  root :to => "expedientes#index"
  get "logout" => "sesiones#destroy", :as => "logout"
  get "login" => "sesiones#new", :as => "login"
  get "signup" => "usuarios#new", :as => "signup"
end

app/models/nota.rb
class Nota < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :denuncia
  attr_accessible :descripcion
end

app/controllers/notas_controller.rb
class NotasController < ApplicationController
  # GET /notas
  # GET /notas.json
  def index
    @notas = Nota.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notas }
    end
  end

  # GET /notas/1
  # GET /notas/1.json
  def show
    @nota = Nota.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nota }
    end
  end

  # GET /notas/new
  # GET /notas/new.json
  def new
    @nota = Nota.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nota }
    end
  end

  # GET /notas/1/edit
  def edit
    @nota = Nota.find(params[:id])
  end

  # POST /notas
  # POST /notas.json
  def create
    @nota = Nota.new(params[:nota])
    @denuncia = Denuncia.find(params[:denuncia_id]) 
    @nota.denuncia = @denuncia
    @nota.usuario = current_user

    respond_to do |format|
      if @nota.save
        format.html { redirect_to @denuncia, notice: 'Nota was successfully created.' }
        format.json { render json: @nota, status: :created, location: @nota }
      else
        format.html { render action: "new" }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notas/1
  # PUT /notas/1.json
  def update
    @nota = Nota.find(params[:id])

    respond_to do |format|
      if @nota.update_attributes(params[:nota])
        format.html { redirect_to @nota, notice: 'Nota was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notas/1
  # DELETE /notas/1.json
  def destroy
    @nota = Nota.find(params[:id])
    @denuncia = @nota.denuncia

    @nota.destroy

    respond_to do |format|
      format.html { redirect_to @denuncia }
      format.json { head :no_content }
    end
  end
end

app/helpers/notas_helper.rb
module NotasHelper
end

app/views/notas/_form.html.erb
<%= form_for(@nota) do |f| %>
  <% if @nota.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nota.errors.count, "error") %> prohibited this nota from being saved:</h2>

      <ul>
      <% @nota.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %><br />
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :denuncia %><br />
    <%= f.text_field :denuncia %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notas/edit.html.erb
<h1>Editing nota</h1>

<%= render 'form' %>

<%= link_to 'Show', @nota %> |
<%= link_to 'Back', notas_path %>

app/views/notas/index.html.erb
<h1>Listing notas</h1>

<table>
  <tr>
    <th>Usuario</th>
    <th>Denuncia</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notas.each do |nota| %>
  <tr>
    <td><%= nota.usuario %></td>
    <td><%= nota.denuncia %></td>
    <td><%= nota.descripcion %></td>
    <td><%= link_to 'Show', nota %></td>
    <td><%= link_to 'Edit', edit_nota_path(nota) %></td>
    <td><%= link_to 'Destroy', nota, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nota', new_nota_path %>

app/views/notas/new.html.erb
<h1>New nota</h1>

<%= render 'form' %>

<%= link_to 'Back', notas_path %>

app/views/notas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuario:</b>
  <%= @nota.usuario %>
</p>

<p>
  <b>Denuncia:</b>
  <%= @nota.denuncia %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @nota.descripcion %>
</p>


<%= link_to 'Edit', edit_nota_path(@nota) %> |
<%= link_to 'Back', notas_path %>