config/routes.rb
Picv::Application.routes.draw do
  

  resources :notas

  resources :denuncias

  resources :expedientes

  resources :sucursales

  resources :municipios

  resources :departamentos

  resources :instituciones

    

  match 'sms/index' => 'sms#index'
  
  resources :archivos

  match 'denuncias/expediente/:id' => 'denuncias#new_con_expediente', :as => :expediente_denuncia

  resources :usuarios
  resources :sesiones
  root :to => "expedientes#index"
  get "logout" => "sesiones#destroy", :as => "logout"
  get "login" => "sesiones#new", :as => "login"
  get "signup" => "usuarios#new", :as => "signup"
end

app/models/denuncia.rb
class Denuncia < ActiveRecord::Base

  TIPOS = ["Violencia Intrafamiliar", "Maltrato a la ninez", "Agresion Sexual"]
  ZONAS = ["Urbana", "Rural", "Marginal"]
  AMBITOS = ["Publico", "Privado"]
  NIVELES_EDUCATIVOS = ["Primaria", "Secundaria", "Bachillerato",
                        "Tecnico","Universitario","Ninguno"]
  RELACIONES = ["Padre", "Madre", "Padrastro",
                "Madrastra","Abuelo","Abuela",
                "Hermano","Hermana","Esposo",
                "Esposa","Ex-Esposo","Ex-Esposa",
                "Amigo","Amiga","Tio","Tia","Desconocido"]
  CONDICIONES = ["Violencia Intrafamiliar", "Maltrato a la ninez", "Agresion Sexual"]
  SEXOS = ["Masculino", "Femenino"]

  has_many :archivos
  has_many :notas
  accepts_nested_attributes_for :archivos, :allow_destroy => true

  belongs_to :usuario
  belongs_to :expediente
  belongs_to :municipio_hechos, :foreign_key => "municipios_hechos_id"
  belongs_to :municipio_agresor, :class_name => "Municipio"
  belongs_to :municipio_trabajo_agresor, :class_name => "Municipio"
  attr_accessible :ambito, :antecendente_criminal_agresor, :condicion_agresor, :descripcion, 
  :direccion_agresor, :direccion_hechos, :direccion_trabajo_agresor, 
  :edad_agresor, :fecha_agresion, :nivel_educativo_agresor, :nombre_agresor, 
  :ocupacion_agresor, :relacion_agresor_victima, :sexo_agresor, :telefono_agresor, 
  :tipo, :tipo_arma_agresor, :trabajo_agresor, :zona_agresor, :zona_hechos,
  :municipio_hechos_id, :municipio_agresor_id,:municipio_trabajo_agresor_id, :archivos_attributes, :expediente_id, :municipio_hechos

   validates :usuario_id, :expediente_id, :municipio_hechos_id, :presence => true
   validates :ambito, :direccion_hechos, :descripcion, :presence => true
   validates :fecha_agresion, :sexo_agresor, :presence => true
   validates :tipo, :presence => true
   validates :zona_hechos,:presence => true
end

app/controllers/denuncias_controller.rb
class DenunciasController < ApplicationController
  
  load_and_authorize_resource
  
  # GET /denuncias
  # GET /denuncias.json
  def index
    @denuncias = Denuncia.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @denuncias }
    end
  end

  # GET /denuncias/1
  # GET /denuncias/1.json
  def show
    @denuncia = Denuncia.find(params[:id])
    @archivo = Archivo.new
    @nota = Nota.new
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @denuncia }
    end
  end

  # GET /denuncias/new
  # GET /denuncias/new.json
  def new
    @denuncia = Denuncia.new
    @expedientes = Expediente.all
    @municipios = Municipio.all 

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @denuncia }
    end
  end

  def new_con_expediente
    @denuncia = Denuncia.new
    @expediente = Expediente.find(params[:id])
    @municipios = Municipio.all 

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @denuncia }
    end
  end

  # GET /denuncias/1/edit
  def edit
    @denuncia = Denuncia.find(params[:id])
    @expedientes = Expediente.all
    @municipios = Municipio.all
    @expediente = @denuncia.expediente
  end

  
  # POST /denuncias
  # POST /denuncias.json
  def create
    @denuncia = Denuncia.new(params[:denuncia])
    @expedientes = Expediente.all
    @municipios = Municipio.all

    @denuncia.usuario = current_user
    @expediente = Expediente.find(params[:expediente_id])
    @denuncia.expediente = @expediente

    respond_to do |format|
      if @denuncia.save
        format.html { redirect_to @expediente, notice: 'Denuncia was successfully created.' }
        format.json { render json: @denuncia, status: :created, location: @denuncia }
      else
        format.html { render action: "new_con_expediente" }
        format.json { render json: @denuncia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /denuncias/1
  # PUT /denuncias/1.json
  def update
    @denuncia = Denuncia.find(params[:id])
    @expedientes = Expediente.all
    @municipios = Municipio.all

    respond_to do |format|
      if @denuncia.update_attributes(params[:denuncia])
        format.html { redirect_to @denuncia, notice: 'Denuncia was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @denuncia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /denuncias/1
  # DELETE /denuncias/1.json
  def destroy
    @denuncia = Denuncia.find(params[:id])
    @denuncia.destroy

    respond_to do |format|
      format.html { redirect_to denuncias_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/denuncias_helper.rb
module DenunciasHelper
end

app/views/denuncias/_form.html.erb
<%= form_for(@denuncia) do |f| %>
  <% if @denuncia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@denuncia.errors.count, "error") %> prohibited this denuncia from being saved:</h2>

      <ul>
      <% @denuncia.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.select(:tipo, Denuncia::TIPOS, {:prompt => false}) %>
  </div>
  <div class="field">
    <%= f.label :direccion_hechos %><br />
    <%= f.text_area :direccion_hechos %>
  </div>
  <div class="field">
    <%= f.label :municipio_hechos %><br />
    <%= collection_select(:denuncia, :municipio_hechos_id, @municipios, :id, :nombre_completo, {:include_blank => 'Selecciona Municipio', :prompt => false})  %>
  </div>
  <div class="field">
    <%= f.label :zona_hechos %><br />
    <%= f.select(:zona_hechos, Denuncia::ZONAS, {:prompt => false}) %>
  </div>
  <div class="field">
    <%= f.label :ambito %><br />
    <%= f.select(:ambito, Denuncia::AMBITOS, {:prompt => false}) %>
  </div>
  <div class="field">
    <%= f.label :fecha_agresion %><br />
    <%= f.datetime_select :fecha_agresion %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :nombre_agresor %><br />
    <%= f.text_field :nombre_agresor %>
  </div>
  <div class="field">
    <%= f.label :edad_agresor %><br />
    <%= f.text_field :edad_agresor %>
  </div>
  <div class="field">
    <%= f.label :sexo_agresor %><br />
    <%= f.select(:sexo_agresor, Denuncia::SEXOS, {:prompt => false, :include_blank => 'Selecciona sexo'}) %>
  </div>
  <div class="field">
    <%= f.label :direccion_agresor %><br />
    <%= f.text_area :direccion_agresor %>
  </div>
  <div class="field">
    <%= f.label :municipio_agresor %><br /> 
    <%= collection_select(:denuncia, :municipio_agresor_id, @municipios, :id, :nombre_completo, {:include_blank => 'Selecciona Municipio'})  %>
  </div>
  <div class="field">
    <%= f.label :zona_agresor %><br />
    <%= f.select(:zona_agresor, Denuncia::ZONAS, {:prompt => false}) %>
  </div>
  <div class="field">
    <%= f.label :nivel_educativo_agresor %><br />
    <%= f.select(:nivel_educativo_agresor, Denuncia::NIVELES_EDUCATIVOS, {:prompt => false}) %>
  </div>
  <div class="field">
    <%= f.label :ocupacion_agresor %><br />
    <%= f.text_field :ocupacion_agresor %>
  </div>
  <div class="field">
    <%= f.label :telefono_agresor %><br />
    <%= f.text_field :telefono_agresor %>
  </div>
  <div class="field">
    <%= f.label :trabajo_agresor %><br />
    <%= f.text_field :trabajo_agresor %>
  </div>
  <div class="field">
    <%= f.label :direccion_trabajo_agresor %><br />
    <%= f.text_area :direccion_trabajo_agresor %>
  </div>
  <div class="field">
    <%= f.label :municipio_trabajo_agresor %><br />
    <%= collection_select(:denuncia, :municipio_trabajo_agresor_id, @municipios, :id, :nombre_completo, {:include_blank => 'Selecciona Municipio', :prompt => false})  %>
  </div>
  <div class="field">
    <%= f.label :relacion_agresor_victima %><br />
    <%= f.select(:relacion_agresor_victima, Denuncia::RELACIONES, {:prompt => false}) %>
  </div>
  <div class="field">
    <%= f.label :condicion_agresor %><br />
    <%= f.select(:condicion_agresor, Denuncia::CONDICIONES, {:prompt => false}) %>
  </div>
  <div class="field">
    <%= f.label :tipo_arma_agresor %><br />
    <%= f.text_field :tipo_arma_agresor %>
  </div>
  <div class="field">
    <%= f.label :antecendente_criminal_agresor %><br />
    <%= f.check_box :antecendente_criminal_agresor %>
  </div>
  <div class="actions">
     <%= hidden_field_tag(:expediente_id, "#{@expediente.id}") %>
    <%= f.submit %>
  </div>
<% end %>

app/views/denuncias/edit.html.erb
<% content_for :content do %>
<h1>Editing denuncia</h1>

<%= render 'form' %>

<%= link_to 'Show', @denuncia %> |
<%= link_to 'Back', denuncias_path %>
<% end %>

<%= render :template => 'layouts/dashboard' %>

app/views/denuncias/index.html.erb
<% content_for :content do %>
<h1>Listing denuncias</h1>

<table class="table table-bordered">
  <tr>
    <th>Usuario</th>
    <th>Expediente</th>
    <th>Tipo</th>
    <th>Direccion hechos</th>
    <th>Municipio hechos</th>
    <th>Zona hechos</th>
    <th>Ambito</th>
    <th>Fecha agresion</th>
    <th>Descripcion</th>
    <th>Nombre agresor</th>
    <th>Edad agresor</th>
    <th>Sexo agresor</th>
    <th>Direccion agresor</th>
    <th>Municipio agresor</th>
    <th>Zona agresor</th>
    <th>Nivel educativo agresor</th>
    <th>Ocupacion agresor</th>
    <th>Telefono agresor</th>
    <th>Trabajo agresor</th>
    <th>Direccion trabajo agresor</th>
    <th>Municipio trabajo agresor</th>
    <th>Relacion agresor victima</th>
    <th>Condicion agresor</th>
    <th>Tipo arma agresor</th>
    <th>Antecendente criminal agresor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @denuncias.each do |denuncia| %>
  <tr>
    <td><%= denuncia.usuario %></td>
    <td><%= denuncia.expediente %></td>
    <td><%= denuncia.tipo %></td>
    <td><%= denuncia.direccion_hechos %></td>
    <td><%= denuncia.municipio_hechos %></td>
    <td><%= denuncia.zona_hechos %></td>
    <td><%= denuncia.ambito %></td>
    <td><%= denuncia.fecha_agresion %></td>
    <td><%= denuncia.descripcion %></td>
    <td><%= denuncia.nombre_agresor %></td>
    <td><%= denuncia.edad_agresor %></td>
    <td><%= denuncia.sexo_agresor %></td>
    <td><%= denuncia.direccion_agresor %></td>
    <td><%= denuncia.municipio_agresor %></td>
    <td><%= denuncia.zona_agresor %></td>
    <td><%= denuncia.nivel_educativo_agresor %></td>
    <td><%= denuncia.ocupacion_agresor %></td>
    <td><%= denuncia.telefono_agresor %></td>
    <td><%= denuncia.trabajo_agresor %></td>
    <td><%= denuncia.direccion_trabajo_agresor %></td>
    <td><%= denuncia.municipio_trabajo_agresor %></td>
    <td><%= denuncia.relacion_agresor_victima %></td>
    <td><%= denuncia.condicion_agresor %></td>
    <td><%= denuncia.tipo_arma_agresor %></td>
    <td><%= denuncia.antecendente_criminal_agresor %></td>
    <td><%= link_to 'Show', denuncia %></td>
    <td><%= link_to 'Edit', edit_denuncia_path(denuncia) %></td>
    <td><%= link_to 'Destroy', denuncia, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Denuncia', new_denuncia_path %>
<% end %>

<%= render :template => 'layouts/dashboard' %>

app/views/denuncias/new.html.erb
<% content_for :content do %>
<h1>New denuncia</h1>

<%= render 'form' %>

<%= link_to 'Back', denuncias_path %>
<% end %>

<%= render :template => 'layouts/dashboard' %>

app/views/denuncias/new_con_expediente.html.erb
<% content_for :content do %>

<ul class="breadcrumb">
                  <li>Estás en:</li>
                  <li>
                    <%= link_to expedientes_path do %>
                        Expedientes
                    <% end %>                  
                    <span class="divider">
                      <span class="icon16 icomoon-icon-arrow-right">/</span>
                    </span>
                  </li>
                  <li>
                    <%= link_to expediente_path(@expediente) do %>
                        Expediente No. <%= @expediente.id %>
                    <% end %>                  
                    <span class="divider">
                      <span class="icon16 icomoon-icon-arrow-right">/</span>
                    </span>
                  </li>
                  <li class="active">Nueva Denuncia</li>
</ul>

<h1>Nueva Denuncia</h1>

<%= render 'form' %>


<% end %>

<%= render :template => 'layouts/dashboard' %>

app/views/denuncias/show.html.erb
<% content_for :content do %>


<ul class="breadcrumb">
                  <li>Estás en:</li>
                  <li>
                    <%= link_to expedientes_path do %>
                        Expedientes
                    <% end %>                  
                    <span class="divider">
                      <span class="icon16 icomoon-icon-arrow-right">/</span>
                    </span>
                  </li>
                  <li>
                    <%= link_to expediente_path(@denuncia.expediente) do %>
                        Expediente No. <%= @denuncia.expediente.id %>
                    <% end %>                  
                    <span class="divider">
                      <span class="icon16 icomoon-icon-arrow-right">/</span>
                    </span>
                  </li>
                  <li class="active">Denuncia No. <%= @denuncia.id %></li>
</ul>

<p id="notice"><%= notice %></p>




<p>
  <b>Usuario:</b>
  <%= @denuncia.usuario.email %>
</p>

<p>
  <b>Tipo:</b>
  <%= @denuncia.tipo %>
</p>

<p>
  <b>Direccion hechos:</b>
  <%= @denuncia.direccion_hechos %>
</p>

<p>
  <b>Municipio hechos:</b>
  
</p>

<p>
  <b>Zona hechos:</b>
  <%= @denuncia.zona_hechos %>
</p>

<p>
  <b>Ambito:</b>
  <%= @denuncia.ambito %>
</p>

<p>
  <b>Fecha agresion:</b>
  <%= @denuncia.fecha_agresion %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @denuncia.descripcion %>
</p>

<p>
  <b>Nombre agresor:</b>
  <%= @denuncia.nombre_agresor %>
</p>

<p>
  <b>Edad agresor:</b>
  <%= @denuncia.edad_agresor %>
</p>

<p>
  <b>Sexo agresor:</b>
  <%= @denuncia.sexo_agresor %>
</p>

<p>
  <b>Direccion agresor:</b>
  <%= @denuncia.direccion_agresor %>
</p>

<p>
  <b>Municipio agresor:</b>
  <%= @denuncia.municipio_agresor.nombre if @denuncia.municipio_agresor %>
</p>

<p>
  <b>Zona agresor:</b>
  <%= @denuncia.zona_agresor %>
</p>

<p>
  <b>Nivel educativo agresor:</b>
  <%= @denuncia.nivel_educativo_agresor %>
</p>

<p>
  <b>Ocupacion agresor:</b>
  <%= @denuncia.ocupacion_agresor %>
</p>

<p>
  <b>Telefono agresor:</b>
  <%= @denuncia.telefono_agresor %>
</p>

<p>
  <b>Trabajo agresor:</b>
  <%= @denuncia.trabajo_agresor %>
</p>

<p>
  <b>Direccion trabajo agresor:</b>
  <%= @denuncia.direccion_trabajo_agresor %>
</p>

<p>
  <b>Municipio trabajo agresor:</b>
  <%= @denuncia.municipio_trabajo_agresor.nombre if @denuncia.municipio_trabajo_agresor %>
</p>

<p>
  <b>Relacion agresor victima:</b>
  <%= @denuncia.relacion_agresor_victima %>
</p>

<p>
  <b>Condicion agresor:</b>
  <%= @denuncia.condicion_agresor %>
</p>

<p>
  <b>Tipo arma agresor:</b>
  <%= @denuncia.tipo_arma_agresor %>
</p>

<p>
  <b>Antecendente criminal agresor:</b>
  <%= @denuncia.antecendente_criminal_agresor %>
</p>


<hr>



<h3>Archivos</h3>

<table class="table table-bordered">
<% @denuncia.archivos.each do |archivo| %>
  <tr>
    <td><%= link_to archivo.archivo_file_name, archivo.archivo.url %></td>
    <td><%= link_to 'Eliminar', archivo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= form_for(@archivo) do |f| %>
  
  <div class="field">
    <%= f.label :archivo %><br />
    <%= f.file_field :archivo %>
  </div>

  <div class="actions">
    <%= hidden_field_tag(:attachable_id, "#{@denuncia.id}") %>
    <%= f.submit %>
  </div>
<% end %>

<hr>

<h3>Notas</h3>

<table class="table table-bordered">
<% @denuncia.notas.each do |nota| %>
  <tr>
    <td><%= nota.descripcion %></td>
    <td><%= link_to 'Eliminar', nota, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= form_for(@nota) do |f| %>

  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="actions">
    <%= hidden_field_tag(:denuncia_id, "#{@denuncia.id}") %>
    <%= f.submit %>
  </div>
<% end %>



<%= link_to 'Editar Denuncia', edit_denuncia_path(@denuncia) %>
<% end %>

<%= render :template => 'layouts/dashboard' %>